export interface Attraction {
  id: number
  name: string
  category: "Historical" | "Nature" | "Wildlife"
  rating: number
  duration: string
  lat: number
  lng: number
  location: string
  description: string
  image: string
  highlights: string[]
  openingHours?: string
  entryFee?: string
  bestTime?: string
  tips?: string[]
  tags?: string[]
}

export const attractions: Attraction[] = [
  {
    id: 1,
    name: "Cape Coast Castle",
    category: "Historical",
    rating: 4.8,
    duration: "2-3 hours",
    lat: 5.1053,
    lng: -1.2466,
    location: "Cape Coast, Central Region",
    description:
      "A UNESCO World Heritage site, this 17th-century castle stands as a powerful reminder of the Atlantic slave trade. Visitors can explore the dungeons, the 'Door of No Return', and the museum which details the history of the trans-Atlantic slave trade. The castle offers stunning views of the Atlantic Ocean, contrasting with its dark history.",
    image: "/cape-coast-castle-ghana.png",
    highlights: ["UNESCO World Heritage", "Historical significance", "Ocean views", "Museum"],
    openingHours: "9:00 AM - 5:00 PM",
    entryFee: "Standard: GH₵ 40 (Locals), $10 (Foreigners)",
    bestTime: "Early morning to avoid heat",
    tips: ["Wear comfortable walking shoes", "Hire a guide for the full history", "Reflectful atmosphere"],
    tags: ["History", "Culture", "Education", "Landmark"],
  },
  {
    id: 2,
    name: "Kakum National Park",
    category: "Nature",
    rating: 4.7,
    duration: "4-5 hours",
    lat: 5.35,
    lng: -1.3833,
    location: "Cape Coast, Central Region",
    description: "Experience the rainforest canopy on suspended walkways 40 meters above the ground. Kakum is one of the few locations in Africa with a canopy walkway, offering a unique perspective of the pristine rainforest. The park is home to forest elephants, bongo antelopes, and over 600 species of butterflies.",
    image: "/placeholder.svg",
    highlights: ["Canopy walkway", "Rainforest", "Wildlife viewing", "Nature trails"],
    openingHours: "6:00 AM - 4:00 PM",
    entryFee: "GH₵ 60 (Adults), GH₵ 20 (Students)",
    bestTime: "Morning for bird watching",
    tips: ["Bring water", "Wear closed shoes", "Canopy walk requires moderate fitness"],
    tags: ["Adventure", "Hiking", "Forest", "Family"],
  },
  {
    id: 3,
    name: "Mole National Park",
    category: "Wildlife",
    rating: 4.6,
    duration: "Full day",
    lat: 9.25,
    lng: -1.85,
    location: "Larabanga, Savannah Region",
    description: "Ghana's largest wildlife refuge, home to elephants, antelopes, and over 300 bird species. Mole offers walking safaris and jeep drives, allowing close encounters with elephants who often frequent the waterholes near the motel. It represents the best wildlife experience in Ghana.",
    image: "/mole-national-park-elephants.png",
    highlights: ["Elephant viewing", "Walking safari", "Bird watching", "Jeep tours"],
    openingHours: "6:00 AM - 5:00 PM",
    entryFee: "Park entrance + Safari fees vary",
    bestTime: "Dry season (Dec-Mar) for wildlife",
    tips: ["Book safaris in advance", "Bring binoculars", "Stay at the Mole Motel or Zaina Lodge"],
    tags: ["Safari", "Animals", "Savannah", "Photography"],
  },
  {
    id: 4,
    name: "Wli Waterfalls",
    category: "Nature",
    rating: 4.5,
    duration: "3-4 hours",
    lat: 7.1167,
    lng: 0.6,
    location: "Wli, Volta Region",
    description: "The highest waterfall in Ghana and West Africa, cascading from a height of approximately 80 meters. The walk to the falls takes you through the Agumatsa Wildlife Sanctuary, where you can see fruit bats and colorful butterflies. The lower falls are easily accessible, while the upper falls require a strenuous hike.",
    image: "/placeholder.svg",
    highlights: ["Highest waterfall", "Hiking trail", "Swimming opportunity", "Bat sanctuary"],
    openingHours: "8:00 AM - 5:00 PM",
    entryFee: "GH₵ 20",
    bestTime: "April to October for full flow",
    tips: ["Bring swimwear", "Prepare for a hike", "Guide required for upper falls"],
    tags: ["Waterfall", "Hiking", "Swimming", "Scenic"],
  },
  {
    id: 5,
    name: "Elmina Castle",
    category: "Historical",
    rating: 4.7,
    duration: "2-3 hours",
    lat: 5.0833,
    lng: -1.35,
    location: "Elmina, Central Region",
    description: "The oldest European building in existence south of the Sahara, built by the Portuguese in 1482. Originally St. George's Castle, it played a significant role in the gold and slave trades. The castle is well-preserved and offers a harrowing insight into the past alongside a bustling fishing harbor view.",
    image: "/placeholder-b1790.png",
    highlights: ["Oldest European building", "Portuguese architecture", "Coastal views", "Fishing harbor"],
    openingHours: "9:00 AM - 4:30 PM",
    entryFee: "Standard fees apply",
    bestTime: "Afternoon for sunset views",
    tips: ["Combine with Cape Coast Castle", "Visit the fishing market nearby"],
    tags: ["History", "Architecture", "UNESCO", "Maritime"],
  },
  {
    id: 6,
    name: "Lake Volta",
    category: "Nature",
    rating: 4.4,
    duration: "Full day",
    lat: 7.5,
    lng: -0.5,
    location: "Volta Region",
    description: "One of the world's largest artificial lakes, formed by the Akosombo Dam. It dominates the landscape of eastern Ghana and offers opportunities for cruises, fishing, and island hopping. Dodi Island and the Digya National Park are popular destinations within the lake basin.",
    image: "/placeholder-9l20x.png",
    highlights: ["Largest artificial lake", "Boat cruises", "Fishing", "Islands"],
    openingHours: "24 Hours",
    entryFee: "Free (activities charged)",
    bestTime: "Weekends for boat cruises",
    tips: ["Take a weekend cruise to Dodi Island", "Try fresh tilapia"],
    tags: ["Water", "Relaxation", "Boating", "Scenic"],
  },
  {
    id: 7,
    name: "Kwame Nkrumah Memorial Park",
    category: "Historical",
    rating: 4.6,
    duration: "1-2 hours",
    lat: 5.5447,
    lng: -0.2036,
    location: "Accra, Greater Accra",
    description: "A mausoleum and park dedicated to Osagyefo Dr. Kwame Nkrumah, the first President of Ghana. The park features a unique futuristic marble mausoleum, a museum housing his personal effects, and beautiful gardens with fountains and statues.",
    image: "/placeholder.svg",
    highlights: ["Mausoleum", "Museum", "Gardens", "Fountains"],
    openingHours: "10:00 AM - 5:00 PM (Mon-Fri), 9:00 AM - 4:00 PM (Sat-Sun)",
    entryFee: "GH₵ 10 (Locals), GH₵ 50 (Foreigners)",
    bestTime: "Late afternoon",
    tips: ["Visit the museum first", "Great for photography"],
    tags: ["History", "Politics", "Architecture", "City"],
  },
  {
    id: 8,
    name: "Aburi Botanical Gardens",
    category: "Nature",
    rating: 4.5,
    duration: "2-3 hours",
    lat: 5.8483,
    lng: -0.1746,
    location: "Aburi, Eastern Region",
    description: "Established in 1890, these cool, mountain gardens offer a refreshing escape from the heat of Accra. Famous for its palm-lined entrance, rare tropical plants, and the 'Tree of Life'. It is a popular spot for picnics and nature walks.",
    image: "/placeholder.svg",
    highlights: ["Palm Walk", "Rare species", "Picnic spots", "Cool climate"],
    openingHours: "8:30 AM - 5:00 PM",
    entryFee: "GH₵ 10",
    bestTime: "Sunday afternoon",
    tips: ["Bring a picnic mat", "Enjoy the fresh palm wine nearby", "Relaxing atmosphere"],
    tags: ["Gardens", "Botany", "Relaxation", "Family"],
  },
  {
    id: 9,
    name: "Larabanga Mosque",
    category: "Historical",
    rating: 4.4,
    duration: "30-60 mins",
    lat: 9.2211,
    lng: -1.8606,
    location: "Larabanga, Savannah Region",
    description: "Known as the 'Mecca of West Africa', this is the oldest mosque in Ghana, dating back to 1421. It is a masterpiece of Sudanese-Sahelian architecture, built with mud and reeds. It is located near the entrance of Mole National Park.",
    image: "/placeholder.svg",
    highlights: ["Ancient architecture", "Mud mosque", "Cultural heritage", "Mystic Stone"],
    openingHours: "Daylight hours",
    entryFee: "Donation based",
    bestTime: "Morning or late afternoon",
    tips: ["Modest dress required", "Combine with Mole National Park visit"],
    tags: ["Culture", "Religion", "Architecture", "Ancient"],
  },
  {
    id: 10,
    name: "Black Star Square",
    category: "Historical",
    rating: 4.3,
    duration: "30-60 mins",
    lat: 5.5492,
    lng: -0.1917,
    location: "Accra, Greater Accra",
    description: "Also known as Independence Square, this vast open space is dominated by the Black Star Gate and the Independence Arch. It is the site for major national parades and festivals. The flame of African Liberation was lit here by Kwame Nkrumah.",
    image: "/placeholder.svg",
    highlights: ["Independence Arch", "Black Star Gate", "Eternal Flame", "Sea views"],
    openingHours: "Open 24 hours",
    entryFee: "Free",
    bestTime: "Early morning or sunset",
    tips: ["Good for quick photo ops", "Can be hot at midday", "Watch out for traffic"],
    tags: ["Monument", "Photography", "City", "Iconic"],
  },
  {
    id: 11,
    name: "Boti Falls",
    category: "Nature",
    rating: 4.5,
    duration: "3-4 hours",
    lat: 6.1833,
    lng: -0.2167,
    location: "Boti, Eastern Region",
    description: "A twin waterfall located in the Yilo Krobo District. The falls are most spectacular during the rainy season when the two streams merge. The area also features the 'Umbrella Rock' and the unique 'Three-Headed Palm Tree', which can be reached by a hike.",
    image: "/placeholder.svg",
    highlights: ["Twin falls", "Umbrella Rock", "Three-headed Palm", "Hiking"],
    openingHours: "8:00 AM - 5:00 PM",
    entryFee: "GH₵ 20",
    bestTime: "Rainy season (Jun-Sep)",
    tips: ["Prepare for a long hike to the rock", "Steps to falls are steep"],
    tags: ["Waterfall", "Hiking", "Adventure", "Nature"],
  },
]

export const categoryColors = {
  Historical: "bg-amber-100 text-amber-800 border-amber-200",
  Nature: "bg-emerald-100 text-emerald-800 border-emerald-200",
  Wildlife: "bg-orange-100 text-orange-800 border-orange-200",
}
